FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY augmenter/ ./augmenter/
COPY trainer/train.py ./train.py
COPY data/ ./data/

CMD ["python", "dashboard.py"]
