FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY explainer/explain.py .
COPY augmenter/ ./augmenter/
COPY data/ ./data/
COPY models/ ./models/

CMD ["python", "explain.py"]

