apiVersion: apps/v1
kind: Deployment
metadata:
  name: explainer
  namespace: ml-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explainer
  template:
    metadata:
      labels:
        app: explainer
    spec:
      containers:
      - name: explainer
        image: ghcr.io/<your-username>/mlpipeline/explainer:latest
        ports:
        - containerPort: 5000
