apiVersion: batch/v1
kind: Job
metadata:
  name: trainer-job
  namespace: ml-pipeline
spec:
  template:
    spec:
      containers:
      - name: trainer
        image: ghcr.io/<your-username>/mlpipeline/trainer:latest
        command: ["python", "train.py"]
      restartPolicy: Never
  backoffLimit: 2
