apiVersion: v1
kind: Service
metadata:
  name: evaluator-service
  namespace: ml-pipeline
spec:
  selector:
    app: evaluator
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP

