name: Kubernetes Deployment

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  KUBE_NAMESPACE: ml-pipeline

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    # 🔧 Build and push all services using the shared root Dockerfile
    - name: Build and push trainer image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/trainer:latest
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          SERVICE=trainer
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push evaluator image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/evaluator:latest
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          SERVICE=evaluator
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push explainer image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/explainer:latest
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          SERVICE=explainer
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push dashboard image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/dashboard:latest
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          SERVICE=dashboard
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # Kubernetes Setup
    - name: Install and configure kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure Kubernetes credentials
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        context: default

    - name: Create namespace if it doesn't exist
      run: |
        kubectl create namespace ${{ env.KUBE_NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -

    - name: Generate Kubernetes manifests
      run: |
        mkdir -p k8s && cat <<EOF > k8s/kubernetes-manifests.yaml
        # same manifest YAML block here (unchanged) ...
        EOF

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/kubernetes-manifests.yaml

    - name: Run trainer job
      run: |
        kubectl wait --for=condition=complete --timeout=300s job/trainer-job -n ${{ env.KUBE_NAMESPACE }} || true

    - name: Verify deployments
      run: |
        kubectl get jobs -n ${{ env.KUBE_NAMESPACE }}
        kubectl get deployments -n ${{ env.KUBE_NAMESPACE }}
        kubectl get services -n ${{ env.KUBE_NAMESPACE }}
        kubectl get pods -n ${{ env.KUBE_NAMESPACE }}
